export type Language = 'en' | 'es';

export const LEGAL_DISCLOSURES = {
  NOT_LEGAL_ADVICE: {
    en: 'This is legal information, not legal advice. For advice about your specific situation, consult a licensed attorney.',
    es: 'Esto es información legal, no asesoramiento legal. Para consejos sobre tu situación especifica, consulta a un abogado licenciado.'
  },
  NO_ATTORNEY_CLIENT: {
    en: 'Using this service does not create an attorney-client relationship. We are not a law firm.',
    es: 'Usar este servicio no crea una relacion abogado-cliente. No somos un bufete de abogados.'
  },
  JURISDICTION_LIMITS: {
    en: 'Legal information may vary by state and jurisdiction. We currently focus on Arizona law.',
    es: 'La información legal puede variar segun el estado y la jurisdicción. Actualmente nos enfocamos en la ley de Arizona.'
  },
  REFERRAL_ELIGIBILITY: {
    en: 'Attorney referrals are based on practice area and location. We do not guarantee representation.',
    es: 'Las referencias de abogados se basan en area de practica y ubicacion. No garantizamos representacion.'
  },
  PRO_BONO_ELIGIBILITY: {
    en: 'Pro bono services have income and case-type requirements. Eligibility is determined by partner organizations.',
    es: 'Los servicios pro bono tienen requisitos de ingresos y tipo de caso. La elegibilidad la determinan las organizaciones asociadas.'
  },
  CONFIDENTIALITY: {
    en: 'Your information is kept confidential and secure. We do not share your data without consent.',
    es: 'Tu información se mantiene confidencial y segura. No compartimos tus datos sin consentimiento.'
  },
  AI_TRANSPARENCY: {
    en: 'Responses are generated by AI and reviewed for accuracy. Always verify important information.',
    es: 'Las respuestas son generadas por IA y revisadas para precision. Siempre verifica la información importante.'
  }
};

export const ACTION_LABELS = {
  START: { en: 'Get Started', es: 'Comenzar' },
  CONTINUE: { en: 'Continue', es: 'Continuar' },
  SUBMIT: { en: 'Submit', es: 'Enviar' },
  LEARN_MORE: { en: 'Learn More', es: 'Saber Mas' },
  FIND_HELP: { en: 'Find Help', es: 'Encontrar Ayuda' },
  TALK_TO_LAWYER: { en: 'Talk to a Lawyer', es: 'Hablar con un Abogado' },
  GET_GUIDANCE: { en: 'Get Guidance', es: 'Obtener Orientación' },
  ASK_QUESTION: { en: 'Ask a Question', es: 'Hacer una Pregunta' },
  APPLY_NOW: { en: 'Apply Now', es: 'Aplicar Ahora' },
  SCHEDULE: { en: 'Schedule', es: 'Programar' },
  DOWNLOAD: { en: 'Download', es: 'Descargar' },
  SHARE: { en: 'Share', es: 'Compartir' },
  BACK: { en: 'Back', es: 'Atras' },
  CANCEL: { en: 'Cancel', es: 'Cancelar' },
  SAVE: { en: 'Save', es: 'Guardar' },
  CLOSE: { en: 'Close', es: 'Cerrar' }
};

export const AFFORDABILITY_MESSAGES = {
  FREE_GUIDANCE: {
    en: 'Free guidance available',
    es: 'Orientación gratuita disponible'
  },
  LOW_COST_OPTIONS: {
    en: 'We help match low-cost options where eligible',
    es: 'Ayudamos a encontrar opciones de bajo costo cuando califiques'
  },
  PRO_BONO_AVAILABLE: {
    en: 'Pro bono services may be available',
    es: 'Servicios pro bono pueden estar disponibles'
  },
  NO_COST_TO_START: {
    en: 'No cost to get started',
    es: 'Sin costo para comenzar'
  },
  INCOME_BASED: {
    en: 'Income-based assistance available',
    es: 'Asistencia basada en ingresos disponible'
  }
};

export const TRUST_SIGNALS = {
  SECURE: { en: 'Private & secure', es: 'Privado y seguro' },
  AVAILABLE_24_7: { en: 'Available 24/7', es: 'Disponible 24/7' },
  NO_SIGNUP: { en: 'No signup required', es: 'Sin registro' },
  CONFIDENTIAL: { en: 'Confidential', es: 'Confidencial' },
  FREE_TO_USE: { en: 'Free to use', es: 'Gratis' },
  REAL_CITATIONS: { en: 'Real legal citations', es: 'Citas legales reales' },
  EXPERT_REVIEWED: { en: 'Expert reviewed', es: 'Revisado por expertos' }
};

export const PAGE_ARCHETYPES = {
  ENTRY: 'entry',
  DECISION: 'decision',
  FORM: 'form',
  RESULTS: 'results',
  SUPPORT: 'support'
} as const;

export type PageArchetype = typeof PAGE_ARCHETYPES[keyof typeof PAGE_ARCHETYPES];

export const ARCHETYPE_CONSTRAINTS: Record<PageArchetype, { maxPrimaryActions: number; maxSecondaryActions: number }> = {
  entry: { maxPrimaryActions: 1, maxSecondaryActions: 2 },
  decision: { maxPrimaryActions: 3, maxSecondaryActions: 1 },
  form: { maxPrimaryActions: 1, maxSecondaryActions: 1 },
  results: { maxPrimaryActions: 2, maxSecondaryActions: 3 },
  support: { maxPrimaryActions: 1, maxSecondaryActions: 2 }
};

export function getDisclosure(key: keyof typeof LEGAL_DISCLOSURES, language: Language): string {
  return LEGAL_DISCLOSURES[key][language];
}

export function getActionLabel(key: keyof typeof ACTION_LABELS, language: Language): string {
  return ACTION_LABELS[key][language];
}

export function getAffordabilityMessage(key: keyof typeof AFFORDABILITY_MESSAGES, language: Language): string {
  return AFFORDABILITY_MESSAGES[key][language];
}

export function getTrustSignal(key: keyof typeof TRUST_SIGNALS, language: Language): string {
  return TRUST_SIGNALS[key][language];
}

export function combineDisclosures(keys: (keyof typeof LEGAL_DISCLOSURES)[], language: Language): string {
  return keys.map(key => LEGAL_DISCLOSURES[key][language]).join(' ');
}

export const AUTH_ERROR_COPY: Record<string, { en: string; es: string }> = {
  'auth.invalid_credentials': {
    en: "That email and password don't match an account. Check both and try again, or reset your password.",
    es: 'Ese correo y contrasena no coinciden. Revisa ambos o restablece tu contrasena.',
  },
  'auth.email_in_use': {
    en: 'An account with this email already exists. Try signing in instead.',
    es: 'Ya existe una cuenta con este correo. Intenta iniciar sesion.',
  },
  'auth.weak_password': {
    en: 'Choose a password with at least 8 characters, including a number or symbol.',
    es: 'Elige una contrasena con al menos 8 caracteres, incluyendo un numero o simbolo.',
  },
  'auth.rate_limited': {
    en: 'Too many attempts. Please wait a minute before trying again.',
    es: 'Demasiados intentos. Espera un minuto antes de intentar de nuevo.',
  },
  'auth.email_not_confirmed': {
    en: 'Confirm your email first. Check your inbox for the confirmation link.',
    es: 'Confirma tu correo primero. Revisa tu bandeja de entrada.',
  },
  'auth.reset_sent': {
    en: 'Check your email for a password reset link. It expires in one hour.',
    es: 'Revisa tu correo para el enlace de restablecimiento. Expira en una hora.',
  },
  'auth.network_error': {
    en: "We couldn't reach our servers. Check your connection and try again.",
    es: 'No pudimos conectar con el servidor. Revisa tu conexion e intenta de nuevo.',
  },
  'auth.generic': {
    en: "We couldn't complete that action. Please try again in a moment.",
    es: 'No pudimos completar esa accion. Intenta de nuevo en un momento.',
  },
};

export function translateAuthError(raw: string | undefined | null, lang?: string): string {
  const language: Language = lang === 'es' ? 'es' : 'en';
  const msg = (raw ?? '').toLowerCase();
  let key: keyof typeof AUTH_ERROR_COPY = 'auth.generic';
  if (!msg) return AUTH_ERROR_COPY[key][language];
  if (msg.includes('invalid login') || msg.includes('invalid credentials') || msg.includes('invalid_credentials')) {
    key = 'auth.invalid_credentials';
  } else if (msg.includes('already registered') || msg.includes('user already') || msg.includes('already exists')) {
    key = 'auth.email_in_use';
  } else if (msg.includes('password') && (msg.includes('short') || msg.includes('weak') || msg.includes('at least'))) {
    key = 'auth.weak_password';
  } else if (msg.includes('rate') || msg.includes('too many')) {
    key = 'auth.rate_limited';
  } else if (msg.includes('not confirmed') || msg.includes('confirm your email')) {
    key = 'auth.email_not_confirmed';
  } else if (msg.includes('network') || msg.includes('fetch') || msg.includes('failed to')) {
    key = 'auth.network_error';
  }
  return AUTH_ERROR_COPY[key][language];
}

export const FIELD_HINTS = {
  EMAIL: {
    en: "We'll send receipts and updates here. We never share your email.",
    es: 'Enviaremos recibos y actualizaciones aquí. Nunca compartimos tu correo.',
  },
  PASSWORD_NEW: {
    en: 'At least 8 characters with a number or symbol.',
    es: 'Al menos 8 caracteres con un numero o simbolo.',
  },
  PHONE: {
    en: 'We only call or text if there is an urgent update on your case.',
    es: 'Solo llamamos o escribimos si hay una actualizacion urgente.',
  },
  ZIP: {
    en: 'Helps us match you with local attorneys and resources.',
    es: 'Nos ayuda a emparejarte con abogados y recursos locales.',
  },
  JURISDICTION: {
    en: 'Choose the state where the issue happened.',
    es: 'Elige el estado donde ocurrio el problema.',
  },
  DESCRIPTION: {
    en: 'A few sentences in your own words is enough. No legal jargon needed.',
    es: 'Unas oraciones en tus propias palabras bastan. No necesitas jerga legal.',
  },
} as const;

export function getFieldHint(key: keyof typeof FIELD_HINTS, language: Language): string {
  return FIELD_HINTS[key][language];
}

