export type ReviewStatus =
  | 'draft'
  | 'submitted'
  | 'pending_conflict_check'
  | 'accepted_by_attorney'
  | 'declined'
  | 'in_review'
  | 'changes_requested'
  | 'completed'
  | 'cancelled'
  | 'refunded';

export type ReviewUrgency = 'standard' | 'expedited' | 'emergency';

export interface AttorneyReviewRequest {
  id: string;
  userId: string | null;
  anonymousSessionId: string | null;
  businessSegment: string;
  jurisdiction: string | null;
  issueArea: string | null;
  triggerReasons: string[];
  urgency: ReviewUrgency;
  documentType: string | null;
  status: ReviewStatus;
  priceCents: number | null;
  scopeAcknowledgedAt: string | null;
  assignedAttorneyId: string | null;
  attorneyAcceptedAt: string | null;
  completedAt: string | null;
  conflictCheckStatus: 'pending' | 'cleared' | 'flagged' | null;
  requestedTurnaround: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ReviewAcknowledgment {
  notLegalAdviceUntilReviewed: boolean;
  attorneyMayDecline: boolean;
  separateEngagement: boolean;
  noGuaranteedOutcome: boolean;
  timelinesAreEstimates: boolean;
  jurisdictionMayAffect: boolean;
}

export const REVIEW_ACKNOWLEDGMENT_TEXTS = {
  en: {
    notLegalAdviceUntilReviewed: 'I understand that documents generated by ezLegal are not legal advice until reviewed by a licensed attorney.',
    attorneyMayDecline: 'I understand that submitting a request does not guarantee attorney availability. An attorney may decline if it falls outside their expertise or involves a conflict.',
    separateEngagement: 'I understand that attorney review is a separate engagement. Attorney-client relationship terms depend on the attorney\'s own engagement terms, not ezLegal.',
    noGuaranteedOutcome: 'I understand that attorney review does not guarantee any particular legal outcome.',
    timelinesAreEstimates: 'I understand that turnaround times are estimates unless confirmed by the assigned attorney.',
    jurisdictionMayAffect: 'I understand that my jurisdiction may affect attorney availability and review scope.',
  },
  es: {
    notLegalAdviceUntilReviewed: 'Entiendo que los documentos generados por ezLegal no son asesoría legal hasta ser revisados por un abogado licenciado.',
    attorneyMayDecline: 'Entiendo que enviar una solicitud no garantiza la disponibilidad de un abogado. Un abogado puede rechazar si cae fuera de su experiencia o involucra un conflicto.',
    separateEngagement: 'Entiendo que la revisión de abogado es un compromiso separado. Los términos de la relación abogado-cliente dependen de los términos del abogado, no de ezLegal.',
    noGuaranteedOutcome: 'Entiendo que la revisión de abogado no garantiza ningún resultado legal en particular.',
    timelinesAreEstimates: 'Entiendo que los plazos de entrega son estimaciones a menos que sean confirmados por el abogado asignado.',
    jurisdictionMayAffect: 'Entiendo que mi jurisdicción puede afectar la disponibilidad del abogado y el alcance de la revisión.',
  },
} as const;

export interface ReviewStatusDisplay {
  label: string;
  description: string;
  color: string;
}

export const REVIEW_STATUS_DISPLAY: Record<ReviewStatus, ReviewStatusDisplay> = {
  draft: { label: 'Draft', description: 'Request started but not yet submitted', color: 'gray' },
  submitted: { label: 'Submitted', description: 'Request submitted, awaiting processing', color: 'blue' },
  pending_conflict_check: { label: 'Conflict Check', description: 'Awaiting conflict of interest clearance', color: 'amber' },
  accepted_by_attorney: { label: 'Accepted', description: 'Attorney accepted, review beginning', color: 'teal' },
  declined: { label: 'Declined', description: 'Attorney declined the request', color: 'red' },
  in_review: { label: 'In Review', description: 'Attorney actively reviewing document', color: 'blue' },
  changes_requested: { label: 'Changes Requested', description: 'Attorney requested additional information', color: 'amber' },
  completed: { label: 'Completed', description: 'Attorney review complete', color: 'green' },
  cancelled: { label: 'Cancelled', description: 'Request cancelled by user', color: 'red' },
  refunded: { label: 'Refunded', description: 'Payment refunded', color: 'slate' },
};

export const ATTORNEY_REVIEW_DISCLOSURES = {
  en: {
    headline: 'Important Information About Attorney Review',
    points: [
      'AI document generation is informational only — it is not legal advice.',
      'Attorney review is only provided after an attorney accepts your request.',
      'Submitting a request does not guarantee that an attorney will be available.',
      'Turnaround times are estimates. Actual timelines depend on attorney availability and case complexity.',
      'Attorney-client relationship terms are set by the reviewing attorney, not by ezLegal.',
      'Your jurisdiction may affect which attorneys are available to review your document.',
      'ezLegal is not a law firm and does not provide legal advice.',
    ],
    notIncluded: [
      'Ongoing legal representation',
      'Court filings or appearances',
      'Legal advice beyond the specific document reviewed',
      'Guarantee of legal outcome',
    ],
  },
  es: {
    headline: 'Información Importante Sobre la Revisión de Abogado',
    points: [
      'La generación de documentos por IA es solo informativa — no es asesoría legal.',
      'La revisión de abogado solo se proporciona después de que un abogado acepta su solicitud.',
      'Enviar una solicitud no garantiza que un abogado estará disponible.',
      'Los plazos de entrega son estimaciones. Los tiempos reales dependen de la disponibilidad del abogado y la complejidad del caso.',
      'Los términos de la relación abogado-cliente los establece el abogado revisor, no ezLegal.',
      'Su jurisdicción puede afectar qué abogados están disponibles para revisar su documento.',
      'ezLegal no es un bufete de abogados y no proporciona asesoría legal.',
    ],
    notIncluded: [
      'Representación legal continua',
      'Presentaciones o comparecencias en tribunal',
      'Asesoría legal más allá del documento específico revisado',
      'Garantía de resultado legal',
    ],
  },
} as const;
