/*
  # Populate Chatbot Prompts

  1. Changes
    - Insert 300 predefined prompts matching LegalBreeze structure
    - Each prompt links to its category and subcategory
    - Covers Adult Guardianship, Consumer Protection, Criminal Matters, 
      Dependency/Juvenile, DUIs, and Employment

  2. Prompt Categories Covered
    - Adult Guardianship (30 prompts): Establishing, Court Process, Responsibilities, Ending, Resources
    - Consumer Protection (28 prompts): Product Issues, Financial, Scams, Contracts, Reporting, Privacy
    - Criminal Matters (82 prompts): Arrest, Defenses, Court Process, Sentencing, Appeals, Representation
    - Dependency/Juvenile (48 prompts): Custody, Court Process, Parental Rights, Support, Emancipation
    - DUIs (34 prompts): Charges, Penalties, Defenses, Long-Term Impact, Court Process
    - Employment (78 prompts): Employee Rights, Contracts, Workplace Policies
*/

DELETE FROM chatbot_prompts;

INSERT INTO chatbot_prompts (id, category_id, subcategory_id, title, prompt_text, is_active) VALUES
  (1, 1, 1, 'What is adult guardianship', 'What exactly is adult guardianship, and why might someone need it?', true),
  (2, 1, 1, 'Guardianship without lawyer', 'Can I establish guardianship for a loved one without hiring a lawyer?', true),
  (3, 1, 1, 'Basic guardianship steps', 'What are the basic steps to get adult guardianship on my own?', true),
  (4, 1, 1, 'Avoid lawyer for finances', 'Is there a way to avoid hiring a lawyer to help my elderly relative with their finances?', true),
  (5, 1, 1, 'DIY guardianship resources', 'Are there DIY resources to help with applying for guardianship?', true),
  (6, 1, 1, 'Temporary guardianship', 'Is there a way to set up temporary guardianship without going through a lawyer?', true),
  (7, 1, 1, 'Risks without attorney', 'What are the risks if I try to apply for guardianship without an attorney?', true),
  (8, 1, 1, 'Free legal aid', 'Are there free or low-cost legal aid services that could help with guardianship?', true),
  (9, 1, 1, 'Create guardianship plan', 'How do I create a solid guardianship plan without paying for a lawyer''s assistance?', true),
  (10, 1, 1, 'Options if cannot afford', 'What other options do I have if I can''t afford guardianship attorney fees?', true),
  (11, 1, 1, 'Help without court', 'What can I do if I think my loved one needs help but doesn''t want to go through a court process?', true),
  (12, 1, 1, 'Fill out paperwork', 'How do I fill out the paperwork for adult guardianship myself?', true),
  (13, 1, 1, 'Lower guardianship costs', 'Are there ways to lower the costs of getting guardianship if I can''t afford an attorney?', true),
  (14, 1, 2, 'Court criteria for guardian', 'What criteria does the court use to decide if someone needs a guardian?', true),
  (15, 1, 2, 'Represent myself in court', 'How complicated is it to represent myself in court for a guardianship hearing?', true),
  (16, 1, 2, 'Documents to prove need', 'What kind of documents do I need to prove someone needs a guardian?', true),
  (17, 1, 2, 'Attending hearing alone', 'What do I need to know about attending a guardianship court hearing on my own?', true),
  (18, 1, 2, 'Agreed vs contested', 'How does the guardianship process differ if the person agrees versus contests it?', true),
  (19, 1, 2, 'Object to guardianship', 'How can I object to someone else trying to get guardianship without having to pay a lawyer?', true),
  (20, 1, 3, 'Financial responsibilities', 'How do I handle the financial responsibilities of guardianship without legal help?', true),
  (21, 1, 3, 'Maintain independence', 'How can I help my loved one stay as independent as possible under guardianship?', true),
  (22, 1, 3, 'Main responsibilities', 'What are the main responsibilities of a guardian, and can I handle them without legal training?', true),
  (23, 1, 4, 'End guardianship', 'Can I end a guardianship without hiring a lawyer?', true),
  (24, 1, 5, 'Common mistakes', 'What are some common mistakes to avoid when applying for guardianship?', true),
  (25, 1, 5, 'Show best person', 'How can I show that I''m the best person to be a guardian without a lawyer''s help?', true),
  (26, 1, 5, 'Guides and resources', 'Are there guides or resources that can help me complete guardianship forms on my own?', true),
  (27, 1, 5, 'Attorney if no disputes', 'Do I need to hire an attorney if there are no disputes about my loved one needing a guardian?', true),
  (28, 1, 5, 'Local resources', 'Are there any local resources or support groups that can help me understand the guardianship process?', true),
  (29, 1, 5, 'State laws self-rep', 'What should I know about guardianship laws in my state if I''m representing myself?', true),
  (30, 1, 5, 'Financial reporting', 'How do I deal with financial reporting requirements as a guardian without an accountant?', true),
  (31, 2, 6, 'Defective product refund', 'What are my rights if a business refuses to provide a refund for a defective product?', true),
  (32, 2, 6, 'Warranty applies', 'How do I know if a warranty applies to my product?', true),
  (33, 2, 6, 'Product recall check', 'How do I check if a product recall affects something I bought?', true),
  (34, 2, 6, 'Car hidden defects', 'What are my rights if my car was sold to me with hidden defects?', true),
  (35, 2, 6, 'Online order never arrived', 'What are my rights if a product I ordered online never arrived?', true),
  (36, 2, 7, 'Unauthorized charges', 'What should I do if a company keeps charging my credit card without my permission?', true),
  (37, 2, 7, 'Hidden fees dispute', 'I was charged hidden fees for a service. How can I dispute them?', true),
  (38, 2, 7, 'Overcharged credit card', 'What are my rights if I was overcharged on a credit card?', true),
  (39, 2, 7, 'Utility bill dispute', 'How can I dispute incorrect charges on my utility bill?', true),
  (40, 2, 7, 'Accidental subscription', 'Is there a way to get my money back for a subscription I accidentally signed up for?', true),
  (41, 2, 7, 'Cancel gym membership', 'How do I cancel a gym membership that keeps billing me?', true),
  (42, 2, 7, 'Debt collection harassment', 'How can I get a debt collection agency to stop harassing me?', true),
  (43, 2, 7, 'Credit reporting error', 'How do I handle a credit reporting error that''s affecting my credit score?', true),
  (44, 2, 8, 'Online scam recovery', 'I think I''ve been scammed online. What steps should I take to get my money back?', true),
  (45, 2, 8, 'Identity theft victim', 'What can I do if I believe I''m a victim of identity theft?', true),
  (46, 2, 8, 'Online order fraud', 'What are my rights if a product I ordered online never arrived? (If due to fraud, also fits here)', true),
  (47, 2, 9, 'Cancel regretted contract', 'Is there a way to cancel a contract I signed but now regret?', true),
  (48, 2, 9, 'Unauthorized service charge', 'What steps can I take if I''m being charged for a service I didn''t authorize?', true),
  (49, 2, 9, 'Travel company no refund', 'What are my options if a travel company cancels my trip and won''t offer a refund?', true),
  (50, 2, 9, 'Company breach contract', 'What can I do if a company breaches their contract with me?', true),
  (51, 2, 10, 'Report misleading ads', 'How can I report a company that is engaging in misleading advertising?', true),
  (52, 2, 10, 'Sue for false claims', 'Can I sue a company for false claims in their advertising?', true),
  (53, 2, 10, 'Report consumer violations', 'How do I report a company for violating consumer protection laws?', true),
  (54, 2, 10, 'Unfair business practice', 'How can I tell if a business practice is unfair or deceptive?', true),
  (55, 2, 10, 'Price increase after reservation', 'Are there laws that protect me from a price increase after I made a reservation?', true),
  (56, 2, 10, 'Class action eligibility', 'How do I find out if I''m eligible for a class action lawsuit?', true),
  (57, 2, 11, 'Personal data safety', 'How can I make sure that my personal data is safe when shopping online?', true),
  (58, 2, 11, 'Stop robocalls', 'How do I stop robocalls or unwanted telemarketing calls?', true),
  (59, 3, 12, 'Accused of crime', 'What should I do if I''ve been accused of a crime I didn''t commit?', true),
  (60, 3, 12, 'Police search rights', 'What are my rights if the police want to search my home or car?', true),
  (61, 3, 12, 'What to say if arrested', 'What should I say or not say if I get arrested?', true),
  (62, 3, 12, 'Refuse police questions', 'What can happen if I refuse to answer police questions?', true),
  (63, 3, 12, 'Traffic stop rights', 'What are my rights if I''m stopped by the police while driving?', true),
  (64, 3, 12, 'Didn''t know illegal', 'Can I get in trouble for something I didn''t know was illegal?', true),
  (65, 3, 12, 'Miss court date', 'What happens if I miss a court date?', true),
  (66, 3, 12, 'Rights violated arrest', 'What should I do if I think my rights were violated during an arrest?', true),
  (67, 3, 12, 'Arraignment hearing', 'What happens at an arraignment hearing?', true),
  (68, 3, 12, 'Warrant check', 'How can I find out if there''s a warrant out for my arrest?', true),
  (69, 3, 12, 'Probable cause meaning', 'What does "probable cause" mean in criminal law?', true),
  (70, 3, 12, 'Witness police question', 'What should I do if I witness a crime and the police want to question me?', true),
  (71, 3, 12, 'Record police legally', 'Can I legally record the police during an encounter?', true),
  (72, 3, 12, 'Posting bail', 'What should I know before posting bail for a family member?', true),
  (73, 3, 12, 'Complaint against officer', 'What''s the process for filing a complaint against a police officer?', true),
  (74, 3, 12, 'Plea bargains', 'How do plea bargains work, and should I consider one?', true),
  (75, 3, 12, 'Challenge arrest warrant', 'Can my lawyer challenge an improperly issued arrest warrant?', true),
  (76, 3, 12, 'Challenge search warrant', 'Can my lawyer challenge a search warrant if it was issued illegally?', true),
  (77, 3, 12, 'Speedy trial violation', 'Can my lawyer dismiss my case if my right to a speedy trial was violated?', true),
  (78, 3, 12, 'Speedy trial rights', 'What rights do I have to a speedy trial?', true),
  (79, 3, 13, 'Assault defenses', 'What defenses are available for someone accused of assault?', true),
  (80, 3, 13, 'Stand your ground', 'How do "stand your ground" or "self-defense" laws work in my state?', true),
  (81, 3, 13, 'Drug possession options', 'If I''m facing drug possession charges, what are my options?', true),
  (82, 3, 13, 'DUI harsher penalties', 'How can I protect myself from harsher penalties in a DUI case?', true),
  (83, 3, 13, 'Refuse breathalyzer', 'Can I refuse to take a breathalyzer test, and what happens if I do?', true),
  (84, 3, 13, 'Challenge illegal evidence', 'Can I challenge evidence that was obtained illegally?', true),
  (85, 3, 13, 'Traffic stop protection', 'How can I protect my rights during a traffic stop?', true),
  (86, 3, 13, 'Beyond reasonable doubt', 'What does "beyond a reasonable doubt" mean in a criminal case?', true),
  (87, 3, 13, 'Brady rule evidence', 'How does my lawyer obtain exculpatory evidence under the Brady rule?', true),
  (88, 3, 13, 'Suppress coerced confession', 'Can I suppress a confession if I was coerced into making it?', true),
  (89, 3, 13, 'Expert testimony', 'Can my lawyer introduce expert testimony in my defense?', true),
  (90, 3, 13, 'Challenge juror bias', 'What factors are considered when challenging a juror for bias?', true),
  (91, 3, 13, 'Remove biased judge', 'Can I request that a judge be removed from my case for bias?', true),
  (92, 3, 13, 'Change of venue', 'Can I request a change of venue if I believe pretrial publicity will affect my case?', true),
  (93, 3, 13, 'Alibi defense notice', 'Can my lawyer file a notice of alibi defense, and what does it involve?', true),
  (94, 3, 13, 'Prior conviction challenge', 'What are common mistakes to avoid when challenging the admissibility of a prior conviction?', true),
  (95, 3, 13, 'Accused of harassment', 'What should I do if someone is accusing me of harassment?', true),
  (96, 3, 13, 'False domestic violence', 'What happens if I''m falsely accused of domestic violence?', true),
  (97, 3, 13, 'Charged with theft', 'What are my options if I''ve been charged with theft?', true),
  (98, 3, 14, 'Memorandum of law', 'What is a memorandum of law, and how does it affect my criminal defense case?', true),
  (99, 3, 14, 'Plea for non-violent', 'What should I know about plea agreements if I''m charged with a non-violent crime?', true),
  (100, 3, 14, 'Pretrial discovery', 'What information is included in a pretrial discovery request, and how can it help my case?', true);

INSERT INTO chatbot_prompts (id, category_id, subcategory_id, title, prompt_text, is_active) VALUES
  (101, 3, 14, 'Drug plea bargain', 'What are the usual terms of a plea bargain in a drug possession case?', true),
  (102, 3, 14, 'Closing argument', 'How does my lawyer prepare a strong closing argument in my defense?', true),
  (103, 3, 14, 'Opening statement', 'What should I expect in my lawyer''s opening statement at trial?', true),
  (104, 3, 14, 'Motion for new trial', 'What mistakes should my lawyer avoid when filing a motion for a new trial?', true),
  (105, 3, 14, 'First-time offender', 'Can my lawyer negotiate a reduction in charges if I''m a first-time offender?', true),
  (106, 3, 14, 'Pretrial hearing response', 'How does my lawyer respond to a prosecution''s motion for a pretrial hearing?', true),
  (107, 3, 14, 'Force prosecution evidence', 'Can my lawyer force the prosecution to hand over evidence in my case?', true),
  (108, 3, 14, 'Defense engagement letter', 'What should be included in a criminal defense attorney''s engagement letter?', true),
  (109, 3, 14, 'Separate charges', 'Can I request that my charges be separated if I''m facing multiple counts?', true),
  (110, 3, 14, 'Juvenile court minors', 'How does juvenile court work for minors accused of a crime?', true),
  (111, 3, 15, 'How bail works', 'How does bail work, and how can I get released before trial?', true),
  (112, 3, 15, 'Misdemeanor consequences', 'What are the possible consequences of a misdemeanor charge?', true),
  (113, 3, 15, 'Felony vs misdemeanor', 'What''s the difference between a felony and a misdemeanor?', true),
  (114, 3, 15, 'Record job housing', 'Will a criminal record affect my ability to get a job or housing?', true),
  (115, 3, 15, 'Expunge charge', 'Can I get a criminal charge expunged from my record?', true),
  (116, 3, 15, 'Reduce sentence probation', 'How can I reduce my sentence or get probation instead of jail time?', true),
  (117, 3, 15, 'First drug offense', 'What are the potential penalties for a first-time drug offense?', true),
  (118, 3, 15, 'First shoplifting', 'What can happen if I''m caught shoplifting for the first time?', true),
  (119, 3, 15, 'Jail for unpaid fines', 'Can I go to jail for unpaid fines or traffic tickets?', true),
  (120, 3, 15, 'Probation violation', 'How does probation work, and what happens if I violate it?', true),
  (121, 3, 15, 'Community service', 'How does community service work as a sentence?', true),
  (122, 3, 15, 'Clemency pardon', 'Can my lawyer request clemency or a pardon for me?', true),
  (123, 3, 15, 'Diversion program', 'What are the benefits of entering a diversion program, and do I qualify?', true),
  (124, 3, 15, 'Deferred prosecution', 'What does a deferred prosecution agreement mean, and is it a good option for me?', true),
  (125, 3, 15, 'DNA testing', 'How does post-conviction DNA testing work, and could it help my case?', true),
  (126, 3, 16, 'Appeal conviction', 'What''s the process for appealing a criminal conviction?', true),
  (127, 3, 16, 'Criminal trial expect', 'What should I expect during a criminal trial?', true),
  (128, 3, 16, 'Set aside guilty plea', 'What mistakes should my lawyer avoid when trying to set aside a guilty plea?', true),
  (129, 3, 16, 'Judgment of acquittal', 'Can my lawyer request a judgment of acquittal after a guilty verdict?', true),
  (130, 3, 16, 'Habeas corpus', 'What is a writ of habeas corpus, and how can it help me challenge my detention?', true),
  (131, 3, 16, 'Expungement process', 'What does the expungement process involve, and do I qualify?', true),
  (132, 3, 16, 'Remove prior conviction', 'Can my lawyer help me remove a prior conviction from my record?', true),
  (133, 3, 17, 'Represent myself criminal', 'Can I represent myself in a criminal case, and is it a good idea?', true),
  (134, 3, 17, 'Prepare without lawyer', 'How can I prepare for a court appearance if I can''t afford a lawyer?', true),
  (135, 3, 17, 'Public defender vs private', 'Can I get a public defender, and how do they compare to private attorneys?', true),
  (136, 3, 17, 'Cannot afford fine', 'What are my options if I can''t afford to pay a criminal fine?', true),
  (137, 3, 17, 'Defense retainer agreement', 'What should I look for in a criminal defense retainer agreement before hiring a lawyer?', true),
  (138, 3, 17, 'Fee agreement expect', 'What should I expect in a criminal defense attorney''s fee agreement?', true),
  (139, 3, 17, 'Conflict of interest', 'What should I know about a criminal defense attorney''s conflict of interest waiver?', true),
  (140, 3, 17, 'Appoint expert witness', 'What should my lawyer consider when asking the court to appoint an expert witness?', true),
  (141, 4, 18, 'Get child back foster', 'What is the process to get my child back from foster care?', true),
  (142, 4, 18, 'Visitation foster care', 'How do I get visitation rights if my child is in foster care?', true),
  (143, 4, 18, 'Relative placement', 'Can my child be placed with a relative instead of foster care?', true),
  (144, 4, 18, 'Prevent permanent placement', 'How can I prevent my child from being permanently placed with another family?', true),
  (145, 4, 18, 'Child rights foster', 'What are my child''s rights if they''re placed in foster care?', true),
  (146, 4, 18, 'Fail reunification plan', 'What happens if I fail to follow the court''s reunification plan?', true),
  (147, 4, 18, 'Request more visitation', 'How do I request more visitation time with my child?', true),
  (148, 4, 18, 'Report abuse neglect', 'What is the process for reporting child abuse or neglect to the court?', true),
  (149, 4, 19, 'Dependency hearing expect', 'What should I expect at a juvenile dependency hearing?', true),
  (150, 4, 19, 'Dispositional hearing', 'What happens during a dispositional hearing in juvenile court?', true),
  (151, 4, 19, 'Dependency review hearing', 'What happens during a dependency review hearing?', true),
  (152, 4, 19, 'Dependency vs family court', 'What is the difference between dependency court and family court?', true),
  (153, 4, 19, 'Dependency outcomes', 'What are the possible outcomes of a dependency court case?', true),
  (154, 4, 19, 'Dependency case length', 'How long does a dependency case typically last?', true),
  (155, 4, 19, 'Miss dependency hearing', 'What happens if I miss a dependency court hearing?', true),
  (156, 4, 19, 'Appeal dependency decision', 'How can I appeal a judge''s decision in a dependency case?', true),
  (157, 4, 19, 'Child speak to judge', 'Can my child speak to the judge in a dependency case?', true),
  (158, 4, 19, 'Reunification best interest', 'How does the court decide whether reunification is in my child''s best interest?', true),
  (159, 4, 19, 'Juvenile court minors crime', 'How does juvenile court work for minors accused of a crime?', true),
  (160, 4, 20, 'Prove fit parent', 'How can I prove I am a fit parent in court?', true),
  (161, 4, 20, 'Parent rights dependency', 'What are my rights as a parent during a dependency case?', true),
  (162, 4, 20, 'Terminate parental rights', 'What factors does the court consider to terminate parental rights?', true),
  (163, 4, 20, 'Regain custody terminated', 'How do I regain custody if my parental rights are terminated?', true),
  (164, 4, 20, 'Challenge CPS investigation', 'Can I challenge a CPS investigation?', true),
  (165, 4, 20, 'CPS false accusation', 'What are the legal options if CPS falsely accuses me of abuse?', true),
  (166, 4, 20, 'Disagree CPS recommendations', 'What should I do if I disagree with CPS recommendations?', true),
  (167, 4, 20, 'Reasons remove child', 'What are the reasons the court may remove my child from my home?', true),
  (168, 4, 21, 'Reunify services', 'What services are available to help me reunify with my child?', true),
  (169, 4, 21, 'Court orders case plan', 'What does it mean if the court orders a case plan?', true),
  (170, 4, 21, 'Prove positive changes', 'How can I prove I have made positive changes in my life for reunification?', true),
  (171, 4, 21, 'Prove stable housing', 'How do I prove to the court that I have stable housing?', true),
  (172, 4, 21, 'Voluntary vs court services', 'What is the difference between voluntary and court-ordered services?', true),
  (173, 4, 21, 'Improve parenting skills', 'How can I show that I am working on improving my parenting skills?', true),
  (174, 4, 21, 'Home visit prep', 'How do I prepare for a home visit by a social worker?', true),
  (175, 4, 21, 'Prepare child court', 'How can I prepare my child for dependency court proceedings?', true),
  (176, 4, 22, 'Court appointed juvenile', 'How can I get a court-appointed lawyer for a juvenile matter?', true),
  (177, 4, 22, 'Guardian ad Litem', 'What is the role of the Guardian ad Litem in my child''s case?', true),
  (178, 4, 23, 'Emancipation petition', 'How do I file an emancipation petition to gain legal independence as a minor?', true),
  (179, 4, 23, 'Emancipation documents', 'What documents do I need to prepare for my emancipation petition?', true),
  (180, 4, 23, 'Financial independence emancipation', 'How do I prove financial independence when applying for emancipation?', true),
  (181, 4, 23, 'Emancipation requirements state', 'What are the legal requirements to become emancipated in my state?', true),
  (182, 4, 23, 'Explain emancipation reasons', 'How do I explain my reasons for seeking emancipation in court?', true),
  (183, 4, 23, 'Emancipation without consent', 'Can I get emancipated without my parents'' consent, and what challenges might I face?', true),
  (184, 4, 23, 'After filing emancipation', 'What happens after I file my emancipation petition—what are the next steps?', true),
  (185, 4, 23, 'Emancipation process time', 'How long does the emancipation process take, and how can I speed it up?', true),
  (186, 4, 23, 'Rights after emancipation', 'What are my rights and responsibilities after I become emancipated?', true),
  (187, 4, 23, 'School financial aid emancipated', 'Can I still go to school and receive financial aid if I am emancipated?', true),
  (188, 4, 23, 'Emancipation denied appeal', 'What should I do if my emancipation petition is denied—can I appeal the decision?', true),
  (189, 5, 24, 'DUI pullover rights', 'What are my rights if I''m pulled over for a DUI?', true),
  (190, 5, 24, 'Refuse breathalyzer DUI', 'Can I refuse a breathalyzer test?', true),
  (191, 5, 24, 'Fail sobriety test', 'What happens if I fail a field sobriety test?', true),
  (192, 5, 24, 'Impaired driving definition', 'What is considered "impaired" driving?', true),
  (193, 5, 24, 'Alcohol tolerance DUI', 'How does alcohol tolerance affect a DUI case?', true),
  (194, 5, 24, 'DUI not driving', 'Can I fight a DUI if I wasn''t actually driving?', true),
  (195, 5, 24, 'BAC impact case', 'What is blood alcohol concentration (BAC) and how does it impact my case?', true),
  (196, 5, 24, 'After DUI arrest', 'What should I do after being arrested for a DUI?', true),
  (197, 5, 24, 'Challenge breath test', 'Can I challenge the results of a breath test?', true),
  (198, 5, 24, 'Refuse blood test DUI', 'What happens if I refuse a blood test for DUI?', true),
  (199, 5, 24, 'Drive on medications', 'Can I drive if I am prescribed medications that impair me?', true),
  (200, 5, 24, 'Prescription drug DUI', 'What happens if my DUI was due to prescription drugs?', true);

INSERT INTO chatbot_prompts (id, category_id, subcategory_id, title, prompt_text, is_active) VALUES
  (201, 5, 24, 'DUI checkpoints', 'How do DUI checkpoints work?', true),
  (202, 5, 25, 'DUI penalties state', 'How severe are DUI penalties in my state?', true),
  (203, 5, 25, 'DUI criminal record', 'Will a DUI show up on my criminal record?', true),
  (204, 5, 25, 'Lose license DUI', 'Can I lose my driver''s license after a DUI?', true),
  (205, 5, 25, 'DUI costs', 'What are the typical costs associated with a DUI charge?', true),
  (206, 5, 25, 'Ignition interlock', 'Will I have to install an ignition interlock device?', true),
  (207, 5, 25, 'DUI employment', 'Can a DUI affect my employment?', true),
  (208, 5, 25, 'Second DUI', 'What happens if I get a second DUI?', true),
  (209, 5, 25, 'DUI with passengers', 'Are DUI penalties worse if there were passengers in the car?', true),
  (210, 5, 25, 'DUI family impact', 'How can a DUI conviction impact my family situation?', true),
  (211, 5, 25, 'Travel DUI record', 'Can I travel internationally with a DUI on my record?', true),
  (212, 5, 25, 'DUI insurance rates', 'How will a DUI affect my car insurance rates?', true),
  (213, 5, 25, 'Alternatives to jail DUI', 'Are there any alternatives to jail for a DUI offense?', true),
  (214, 5, 26, 'Reduce DUI penalties', 'Is there any way to reduce DUI penalties?', true),
  (215, 5, 26, 'DUI dismissed', 'Can I get a DUI charge dismissed?', true),
  (216, 5, 26, 'DUI defenses', 'What defenses are there against DUI charges?', true),
  (217, 5, 26, 'Programs avoid jail DUI', 'Are there any programs to help avoid jail time for a DUI?', true),
  (218, 5, 27, 'Expunge DUI', 'How can I get my DUI record expunged?', true),
  (219, 5, 27, 'Alcohol education classes', 'Will I need to take alcohol education classes?', true),
  (220, 5, 28, 'Lawyer first DUI', 'Do I need a lawyer for a first-time DUI?', true),
  (221, 5, 28, 'DUI case duration', 'How long does a DUI case usually take?', true),
  (222, 5, 28, 'DUI court expect', 'What should I expect in court for a DUI?', true),
  (223, 6, 29, 'Employee rights', 'What are my rights as an employee?', true),
  (224, 6, 29, 'Fired no valid reason', 'What are my rights if I am fired without a valid reason?', true),
  (225, 6, 29, 'Not paid overtime', 'What should I do if I am not being paid overtime?', true),
  (226, 6, 29, 'Fired medical leave', 'Can my employer fire me for taking medical leave?', true),
  (227, 6, 29, 'Rights laid off', 'What are my rights if I am laid off?', true),
  (228, 6, 29, 'Work holidays required', 'Can my employer require me to work on holidays?', true),
  (229, 6, 29, 'Notice before termination', 'How much notice must my employer give me before termination?', true),
  (230, 6, 29, 'Final paycheck refused', 'What can I do if my boss refuses to give me my final paycheck?', true),
  (231, 6, 29, 'Monitor work computer', 'Is it legal for my employer to monitor my work computer?', true),
  (232, 6, 29, 'Prove wrongful termination', 'How do I prove wrongful termination?', true),
  (233, 6, 29, 'Employer retaliation', 'What are my rights if my employer is retaliating against me?', true),
  (234, 6, 29, 'Forced off clock', 'What can I do if I am being forced to work off the clock?', true),
  (235, 6, 29, 'Unemployment benefits', 'Do I qualify for unemployment benefits after being terminated?', true),
  (236, 6, 29, 'Refuse overtime', 'Can I refuse to work overtime without being fired?', true),
  (237, 6, 29, 'Change job description', 'Is my employer allowed to make changes to my job description?', true),
  (238, 6, 29, 'No breaks allowed', 'What should I do if my employer is not allowing me to take breaks?', true),
  (239, 6, 29, 'Discuss salary coworkers', 'Can I get in trouble for discussing my salary with coworkers?', true),
  (240, 6, 29, 'Not paid on time', 'What steps should I take if my employer does not pay me on time?', true),
  (241, 6, 29, 'Unfairly disciplined', 'How do I handle being unfairly disciplined at work?', true),
  (242, 6, 29, 'Full-time to part-time', 'Can my employer change my employment status from full-time to part-time?', true),
  (243, 6, 29, 'Workplace investigation rights', 'What are my rights during a workplace investigation?', true),
  (244, 6, 29, 'Fired wage concerns', 'Can I be fired for raising concerns about wage issues?', true),
  (245, 6, 29, 'Supervisor bullying', 'How do I deal with bullying from my supervisor?', true),
  (246, 6, 29, 'Deduct paycheck', 'Is my employer allowed to deduct money from my paycheck?', true),
  (247, 6, 29, 'Age discrimination', 'What protections do I have against age discrimination at work?', true),
  (248, 6, 29, 'Unpaid training', 'Can I refuse to attend unpaid training outside of my work hours?', true),
  (249, 6, 29, 'Care for sick family', 'What are my rights if I need to care for a sick family member?', true),
  (250, 6, 29, 'Termination letter rights', 'What should I do if I receive a termination letter—what are my rights?', true),
  (251, 6, 29, 'Non-compete agreement', 'What are my rights if my employer asks me to sign a non-compete agreement?', true),
  (252, 6, 29, 'Workers comp rights', 'What are my rights under my employer''s workers'' compensation policy?', true),
  (253, 6, 29, 'Discrimination settlement', 'What should I consider before signing a settlement agreement in a workplace discrimination case?', true),
  (254, 6, 29, 'ADA accommodations request', 'How do I request reasonable accommodations under the ADA at my workplace?', true),
  (255, 6, 29, 'Disciplinary actions rights', 'What disciplinary actions can my employer take against me, and what rights do I have?', true),
  (256, 6, 29, 'Temporary employment rights', 'What are my rights under a temporary employment agreement?', true),
  (257, 6, 29, 'Overtime policy rights', 'What are my rights regarding overtime pay under my employer''s overtime policy?', true),
  (258, 6, 29, 'Challenge accommodation denial', 'How can I challenge a denial of my reasonable accommodation request?', true),
  (259, 6, 29, 'Flexible work rights', 'What are my rights in a flexible work arrangement policy?', true),
  (260, 6, 29, 'File harassment complaint', 'How do I file a complaint for workplace harassment?', true),
  (261, 6, 29, 'Report unsafe conditions', 'What are the steps to report unsafe working conditions?', true),
  (262, 6, 29, 'Discrimination at work', 'What should I do if I am experiencing discrimination at work?', true),
  (263, 6, 30, 'Force non-compete', 'Can my employer force me to sign a non-compete agreement?', true),
  (264, 6, 30, 'Negotiate severance', 'How can I negotiate better severance pay?', true),
  (265, 6, 30, 'Independent contractor status', 'How do I know if I am classified correctly as an independent contractor?', true),
  (266, 6, 30, 'Employment contract terms', 'What should be included in an Employment Contract to protect both employer and employee rights?', true),
  (267, 6, 30, 'Freelance services agreement', 'How do I create a Freelance Services Agreement when hiring an independent contractor?', true),
  (268, 6, 30, 'Independent contractor clauses', 'What key clauses should be included in an Independent Contractor Agreement?', true),
  (269, 6, 30, 'Draft non-compete', 'How do I draft a Non-Compete Agreement to prevent employees from working for competitors?', true),
  (270, 6, 30, 'Consulting agreement terms', 'What should be included in a Consulting Agreement for my business clients?', true),
  (271, 6, 30, 'Request NDA employer', 'How can I request an NDA from my employer to protect my confidential work information?', true),
  (272, 6, 30, 'Severance agreement review', 'What should be included in my severance agreement before I sign it?', true),
  (273, 6, 30, 'Employment contract key terms', 'What key terms should I look for in my employment contract?', true),
  (274, 6, 30, 'Standard contractor terms', 'What are the standard terms I should expect in an independent contractor agreement?', true),
  (275, 6, 30, 'Executive employment expect', 'What should I expect in an executive employment agreement?', true),
  (276, 6, 30, 'Arbitration agreement signing', 'What should I know about signing an arbitration agreement with my employer?', true),
  (277, 6, 30, 'Severance pay terms', 'What are the typical terms of a severance pay agreement, and should I negotiate?', true),
  (278, 6, 30, 'IP agreement employee', 'What should I know about signing an intellectual property agreement as an employee?', true),
  (279, 6, 30, 'Employment contract negotiate', 'What are the essential terms of an Employment Contract that I should negotiate?', true),
  (280, 6, 30, 'Contractor agreement aware', 'What are the key terms in an Independent Contractor Agreement I should be aware of?', true),
  (281, 6, 30, 'Work-for-hire clauses', 'What clauses should be included in a Work-for-Hire Agreement for a freelancer?', true),
  (282, 6, 30, 'Collective bargaining expect', 'What should I expect in a Collective Bargaining Agreement between my employer and my labor union?', true),
  (283, 6, 31, 'Criminal record hiring', 'Can my employer ask about my criminal record during hiring?', true),
  (284, 6, 31, 'Disability accommodations', 'How do I request reasonable accommodations for a disability?', true),
  (285, 6, 31, 'Harassment policy', 'How can I ensure my workplace has a harassment policy that protects employees?', true),
  (286, 6, 31, 'Workplace safety policies', 'What workplace safety policies should my employer have to protect employees?', true),
  (287, 6, 31, 'Family medical leave policy', 'What should be included in my company''s family and medical leave policy?', true),
  (288, 6, 31, 'Social media policy rights', 'What should I know about my company''s social media policy and my rights?', true),
  (289, 6, 31, 'Employee handbook startup', 'What should be included in my startup''s employee handbook to protect workers?', true),
  (290, 6, 31, 'Drug alcohol policies', 'What drug and alcohol policies should my workplace have, and how do they affect me?', true),
  (291, 6, 31, 'Violence prevention policy', 'What should my employer include in a workplace violence prevention policy?', true),
  (292, 6, 31, 'Telecommuting policy', 'What should be in a telecommuting policy for remote employees like me?', true),
  (293, 6, 31, 'Sexual harassment training', 'What should be covered in my employer''s sexual harassment prevention training?', true),
  (294, 6, 31, 'Anti-discrimination policy', 'What should be included in my employer''s anti-discrimination policy?', true),
  (295, 6, 31, 'EEO policy', 'What should be included in my company''s equal employment opportunity (EEO) policy?', true),
  (296, 6, 31, 'Vacation PTO policy', 'How does my employer''s vacation and paid time off policy affect me?', true),
  (297, 6, 31, 'Conflict of interest policy', 'What should I be aware of in my company''s conflict of interest policy?', true),
  (298, 6, 31, 'Dress code policy', 'What should be in my employer''s dress code policy, and can they enforce it?', true),
  (299, 6, 31, 'Workplace privacy policy', 'How does a workplace privacy policy protect my personal data at work?', true),
  (300, 6, 31, 'Safety training construction', 'What should be covered in workplace safety training for construction workers?', true);

SELECT setval('chatbot_prompts_id_seq', 301, false);
