/*
  # Image SEO system

  1. New tables
    - `image_catalog` — canonical record per image asset. Tracks file path,
      descriptive slug, alt_en / alt_es, width, height, format, byte size,
      variants (srcset widths as JSON), caption, license, and whether the
      asset should be included in the image sitemap.
    - `image_audit_runs` — aggregate readings per CI run.
    - `image_audit_results` — one row per flagged <img> (missing alt,
      missing dimensions, oversize file, missing lazy loading, non-descriptive
      filename, etc.) with severity + fix suggestion.

  2. Security
    - RLS enabled on all three tables.
    - `image_catalog` public SELECT when is_public = true (needed so the
      image sitemap edge function can read without auth); admin-only writes.
    - Audit tables: admin SELECT only; inserts happen via service-role key.

  3. Notes
    - An image_sitemap is generated by a dedicated edge function from the
      `image_catalog` rows flagged `in_sitemap = true`.
*/

CREATE TABLE IF NOT EXISTS image_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  file_path text NOT NULL,
  page_url text NOT NULL DEFAULT '',
  alt_en text NOT NULL,
  alt_es text NOT NULL DEFAULT '',
  caption text NOT NULL DEFAULT '',
  width integer NOT NULL DEFAULT 0,
  height integer NOT NULL DEFAULT 0,
  format text NOT NULL DEFAULT 'webp',
  byte_size integer NOT NULL DEFAULT 0,
  variants jsonb NOT NULL DEFAULT '[]'::jsonb,
  license text NOT NULL DEFAULT '',
  geo_location text NOT NULL DEFAULT '',
  is_public boolean NOT NULL DEFAULT true,
  in_sitemap boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_image_catalog_page_url ON image_catalog(page_url);
CREATE INDEX IF NOT EXISTS idx_image_catalog_sitemap ON image_catalog(in_sitemap) WHERE in_sitemap = true;

CREATE TABLE IF NOT EXISTS image_audit_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  commit_sha text NOT NULL DEFAULT '',
  total_files integer NOT NULL DEFAULT 0,
  total_images integer NOT NULL DEFAULT 0,
  flagged_images integer NOT NULL DEFAULT 0,
  missing_alt integer NOT NULL DEFAULT 0,
  missing_dimensions integer NOT NULL DEFAULT 0,
  missing_lazy integer NOT NULL DEFAULT 0,
  non_descriptive_name integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS image_audit_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL REFERENCES image_audit_runs(id) ON DELETE CASCADE,
  file_path text NOT NULL,
  line_number integer NOT NULL,
  src text NOT NULL DEFAULT '',
  alt_text text NOT NULL DEFAULT '',
  issue_type text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('info','warning','error')),
  suggestion text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_image_audit_results_run ON image_audit_results(run_id);

ALTER TABLE image_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE image_audit_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE image_audit_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read public catalog entries"
  ON image_catalog FOR SELECT
  TO anon, authenticated
  USING (is_public = true);

CREATE POLICY "Admins can insert catalog entries"
  ON image_catalog FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true));

CREATE POLICY "Admins can update catalog entries"
  ON image_catalog FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true));

CREATE POLICY "Admins can delete catalog entries"
  ON image_catalog FOR DELETE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true));

CREATE POLICY "Admins can read image audit runs"
  ON image_audit_runs FOR SELECT
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true));

CREATE POLICY "Admins can read image audit results"
  ON image_audit_results FOR SELECT
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = (SELECT auth.uid()) AND profiles.is_admin = true));

INSERT INTO image_catalog (slug, file_path, page_url, alt_en, alt_es, width, height, format, byte_size, in_sitemap)
VALUES (
  'ezlegal-ai-logo',
  '/red-and-grey-minamali-business-card-2-1-2.svg',
  '/',
  'ezLegal.ai logo, AI-powered legal guidance for Tucson and Arizona',
  'Logotipo de ezLegal.ai, asistencia legal con IA para Tucson y Arizona',
  240, 60, 'svg', 27000, true
)
ON CONFLICT (slug) DO NOTHING;
